version: '3.8'

services:
  database:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3906:3306'
    volumes:
      - ./my-db:/var/lib/mysql
  php:
    container_name: php-spellcheck
    build:
      context: ./php
    volumes:
      - ./src:/var/bin
    depends_on:
      - database
